### ISSUE TITLE
Stream window

### ISSUE THREAD

**Issue by IvanSimen** [alew3/faceit_live3#26]
i'm sorry for stupid question, BUT what does it mean "Stream Window"? It's a camera window?

**Comment by IvanSimen** [comment]
- create scene
- add window capture
- choose  "Stream window" (camera window?)
- add filter VirtualCAM
- start VirtualCAM from tools
- test Hangout and choose OBS cam
- run the program
       conda activate
       python faceit_live.py (need to go to right path.... cd faceit_live3)
...and nothing

CUDA is available:  True
Device Name: GeForce RTX 3070 Laptop GPU
Device Count: 1
CUDA:  10.1
cuDNN 7501
Device 0
Scanning /media folder for images to use...
./media/oliver.jpg
./media/oliver2.jpg
webcam dimensions = 0.0 x 0.0 #Why?
 ..... 10-15 min delay
 Press C to center Webcam, Press B/N for previous/next image in media directory, T to alter between relative and absolute transformation, Q to quit
Traceback (most recent call last):
  File "faceit_live.py", line 285, in <module>
    main()
  File "faceit_live.py", line 124, in main
    frame = cv2.resize(frame, (640, 480))
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4045: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

 PLEASE HELP!)

**Comment by IvanSimen** [comment]
> i'm sorry for stupid question, BUT what does it mean "Stream Window"? It's a camera window?

ok, "stream window" it's window that run after faceit_live.py activate

**Comment by yanis446** [comment]
> 
> 
>     * create scene
> 
>     * add window capture
> 
>     * choose  "Stream window" (camera window?)
> 
>     * add filter VirtualCAM
> 
>     * start VirtualCAM from tools
> 
>     * test Hangout and choose OBS cam
> 
>     * run the program
>       conda activate
>       python faceit_live.py (need to go to right path.... cd faceit_live3)
>       ...and nothing
> 
> 
> CUDA is available: True
> Device Name: GeForce RTX 3070 Laptop GPU
> Device Count: 1
> CUDA: 10.1
> cuDNN 7501
> Device 0
> Scanning /media folder for images to use...
> ./media/oliver.jpg
> ./media/oliver2.jpg
> webcam dimensions = 0.0 x 0.0 #Why?
> ..... 10-15 min delay
> Press C to center Webcam, Press B/N for previous/next image in media directory, T to alter between relative and absolute transformation, Q to quit
> Traceback (most recent call last):
> File "faceit_live.py", line 285, in
> main()
> File "faceit_live.py", line 124, in main
> frame = cv2.resize(frame, (640, 480))
> cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4045: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
> 
> PLEASE HELP!)

How do I access CUDA? I have tried to downloading it but it gives me 403 error messages
